<Project>
	<PropertyGroup>
		<Version>1.0.0</Version>
		
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageOutputPath>..\..\packages\</PackageOutputPath>
		<PackageProjectUrl>https://github.com/RobertLeisner/Bodoconsult.Database</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>

		<Company>Bodoconsult EDV-Dienstleistungen GmbH</Company>
		<Copyright>Bodoconsult EDV-Dienstleistungen GmbH</Copyright>
		<Authors>Robert Leisner</Authors>

		<RepositoryUrl>https://github.com/RobertLeisner/Bodoconsult.Database</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<NeutralLanguage>en</NeutralLanguage>
	</PropertyGroup>
</Project>