<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>

		<!--General Nuget packaging-->
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<Deterministic>False</Deterministic>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<!--Package specific-->
		<PackageId>Bodoconsult.Database.Sqlite</PackageId>
		<PackageTags>System.Data Datatable SQL exec Sqlite DataReader</PackageTags>
		<Description>Simple .NET database layer for Sqlite based on System.Data intended for mainly read-only data access i.e. for reporting purposes or similar read-only data access</Description>
		<PackageReleaseNotes>Migration to .Net 8 and new namespace</PackageReleaseNotes>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>

		<!-- PDB Configuration -->
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<EmbedAllSources>false</EmbedAllSources>

		<!-- Allow PDBs in the main package -->
		<!--
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>-->

		<!-- Generate symbols package (.snupkg) -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<!-- Modern symbols package format -->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE.md" Link="LICENSE.md" Pack="true" PackagePath="\" />
		<None Include="..\..\doc\Bodoconsult.Database.Sqlite\README.md" Link="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Bodoconsult.Database\Bodoconsult.Database.csproj" />
	</ItemGroup>

</Project>
