<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BodoFileTransferCore.Business\BodoFileTransferCore.Business.csproj" />
    <ProjectReference Include="..\BodoFileTransferCore.Ui\BodoFileTransferCore.Ui.csproj" />
    <ProjectReference Include="..\BodoFileTransferCore\BodoFileTransferCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TestData\" />
  </ItemGroup>

</Project>
