<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\Entypo.ttf" />
	  <None Remove="Resources\Localization\de.txt" />
	  <None Remove="Resources\Localization\en.txt" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\aligncenter.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\alignjustify.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\alignleft.PNG" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\alignright.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\codeblock.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\codeinline.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\editcopy.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\editcut.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\editpaste.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\editredo.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\editundo.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\filesave.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\fontbold.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\fontgrow.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\fontitalic.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\fontshrink.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\fontunderline.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\indentdecrease.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\indentincrease.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\listbullets.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\listnumbers.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\LogonImage.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\normaltext.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\PrintDocument.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\save.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\separator.png" />
	  <None Remove="Resources\Styling\BitmapGraphics\Assets\test.jpg" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Resources\Localization\de.txt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\Localization\en.txt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="ReactiveUI.WPF" Version="*" />
		<PackageReference Include="ReactiveUI.SourceGenerators" Version="*" PrivateAssets="all" />
		<PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" Version="*" PrivateAssets="all" />
		<PackageReference Include="MahApps.Metro" Version="2.4.11" />
		<PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Bodoconsult.App.Abstractions\Bodoconsult.App.Abstractions.csproj" />
	  <ProjectReference Include="..\Bodoconsult.App.Wpf\Bodoconsult.App.Wpf.csproj" />
	  <ProjectReference Include="..\Bodoconsult.App\Bodoconsult.App.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Resources\Styling\BitmapGraphics\Icons\" />
	  <Folder Include="Resources\Styling\VectorGraphics\Assets\" />
	  <Folder Include="Resources\Styling\VectorGraphics\Icons\" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Resources\Entypo.ttf" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\aligncenter.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\alignjustify.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\alignleft.PNG" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\alignright.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\codeblock.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\codeinline.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\editcopy.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\editcut.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\editpaste.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\editredo.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\editundo.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\filesave.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\fontbold.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\fontgrow.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\fontitalic.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\fontshrink.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\fontunderline.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\indentdecrease.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\indentincrease.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\listbullets.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\listnumbers.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\LogonImage.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\normaltext.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\PrintDocument.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\save.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\separator.png" />
	  <Resource Include="Resources\Styling\BitmapGraphics\Assets\test.jpg" />
	</ItemGroup>

</Project>
