<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>False</Deterministic>
		<AssemblyName>BodoFtpTransfer.Business</AssemblyName>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Resources\Database.sql" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\Database.sql" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="log4net" Version="3.5.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\src\Bodoconsult.App.Abstractions\Bodoconsult.App.Abstractions.csproj" />
		<ProjectReference Include="..\..\..\src\Bodoconsult.App.DataProtection\Bodoconsult.App.DataProtection.csproj" />
		<ProjectReference Include="..\..\..\src\Bodoconsult.App\Bodoconsult.App.csproj" />
		<ProjectReference Include="..\..\..\src\Bodoconsult.Database.Sqlite\Bodoconsult.Database.Sqlite.csproj" />
		<ProjectReference Include="..\..\..\src\Bodoconsult.Web.Ftp\Bodoconsult.Web.Ftp.csproj" />
	</ItemGroup>

</Project>
