<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="MainWindow1.xaml.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Page Remove="MainWindow1.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="appsettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="log4net.config">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Bodoconsult.App.Abstractions\Bodoconsult.App.Abstractions.csproj" />
		<ProjectReference Include="..\..\src\Bodoconsult.App.Wpf.ReactiveUI\Bodoconsult.App.Wpf.ReactiveUI.csproj" />
		<ProjectReference Include="..\..\src\Bodoconsult.App.Wpf\Bodoconsult.App.Wpf.csproj" />
		<ProjectReference Include="..\..\src\Bodoconsult.App\Bodoconsult.App.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ReactiveUI.WPF" Version="*" />
		<PackageReference Include="ReactiveUI.SourceGenerators" Version="*" PrivateAssets="all" />
		<PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" Version="*" PrivateAssets="all" />
		<PackageReference Include="MahApps.Metro" Version="2.4.11" />
		<PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
	</ItemGroup>

</Project>
