<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

	  <TargetFramework>net9.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>disable</Nullable>
	  <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
	  <Deterministic>False</Deterministic>

	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageOutputPath>..\..\packages\</PackageOutputPath>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <RepositoryType>git</RepositoryType>
	  <PackageTags>OpenXml Excel xlsx database DataTable</PackageTags>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <Description>Library to export database data like System.Data.DataTable as xlsx Excel files</Description>
	  <PackageReleaseNotes>Enhancements, new features and bugfixes</PackageReleaseNotes>
	  <PackageProjectUrl>https://github.com/Bodoconsult/Bodoconsult.AppInfrastructure</PackageProjectUrl>
	  <NeutralLanguage>en</NeutralLanguage>

	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <NeutralLanguage>en</NeutralLanguage>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>

	  <IncludeSymbols>true</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
	  <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ExcelDocument.cs" />
    <Compile Remove="ExcelDocumentStyles.cs" />
    <Compile Remove="ExcelOpenXml.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
  </ItemGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE.md" Link="LICENSE.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\..\doc\Bodoconsult.Office\README.md" Link="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Bodoconsult.App.Abstractions\Bodoconsult.App.Abstractions.csproj" />
	</ItemGroup>

</Project>
