<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="ScottPlot" Version="5.1.59" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bodoconsult.Charting.Base\Bodoconsult.Charting.Base.csproj" />
    <ProjectReference Include="..\..\src\Bodoconsult.Charting\Bodoconsult.Charting.csproj" />
    <ProjectReference Include="..\..\src\Bodoconsult.Drawing.SkiaSharp\Bodoconsult.Drawing.SkiaSharp.csproj" />
  </ItemGroup>

</Project>
