<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>false</Deterministic>
		<AssemblyName>BodoFileTransfer</AssemblyName>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appSettings.json" />
		<None Remove="log4net.config" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="appSettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="log4net.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="log4net" Version="3.3.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BodoFileTransfer.Business\BodoFileTransfer.Business.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Db_Install\" />
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio>
			<UserProperties appsettings_1json__JsonSchema="" />
		</VisualStudio>
	</ProjectExtensions>

</Project>
