<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0.0-windows</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<PackageId>Bodoconsult.Database.Dbase</PackageId>
		<PackageTags>dbase;dbf;migration</PackageTags>
		<Description>Tools for reading DBF files from .NET 8 or later</Description>
		<PackageReleaseNotes>New implementation</PackageReleaseNotes>
		<PackageProjectUrl>https://github.com/RobertLeisner/Bodoconsult.Database</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>

		<!-- PDB Configuration -->
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<EmbedAllSources>false</EmbedAllSources>

		<!-- Allow PDBs in the main package -->
		<!--
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>-->

		<!-- Generate symbols package (.snupkg) -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<!-- Modern symbols package format -->

	</PropertyGroup>

	<ItemGroup>
		<Content Include="..\..\LICENSE.md" Link="LICENSE.md" Pack="true" PackagePath="\" />
		<None Include="..\..\doc\Bodoconsult.Database.Dbase\README.md" Link="README.md" Pack="true" PackagePath="\">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="ImportTasks\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Bodoconsult.App\Bodoconsult.App.csproj" />
	  <ProjectReference Include="..\Bodoconsult.Database.Ef.SqlServer\Bodoconsult.Database.Ef.SqlServer.csproj" />
	  <ProjectReference Include="..\Bodoconsult.Database.Ef\Bodoconsult.Database.Ef.csproj" />
	</ItemGroup>

</Project>
