<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bodoconsult.App\Bodoconsult.App.csproj" />
    <ProjectReference Include="..\..\src\Bodoconsult.Database.Ef\Bodoconsult.Database.Ef.csproj" />
  </ItemGroup>

</Project>
