<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<Deterministic>False</Deterministic>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<PackageId>Bodoconsult.Database.Postgres</PackageId>
		<PackageTags>System.Data PostgreSql Datatable SQL exec</PackageTags>
		<Description>Simple .NET database layer for PostgreSQL based on System.Data intended for mainly read-only data access i.e. for reporting purposes</Description>
		<PackageReleaseNotes>Migration to .Net 8 and new namespace</PackageReleaseNotes>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>

		<!-- PDB Configuration -->
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<EmbedAllSources>false</EmbedAllSources>

		<!-- Allow PDBs in the main package -->
		<!--
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>-->

		<!-- Generate symbols package (.snupkg) -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<!-- Modern symbols package format -->

	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="MetaData\BaseMetaDataService.cs" />
		<Compile Remove="MetaData\IMetaDataService.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE.md" Link="LICENSE.md" Pack="true" PackagePath="\" />
		<None Include="..\..\doc\Bodoconsult.Database.Postgres\README.md" Link="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Npgsql" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Bodoconsult.Database\Bodoconsult.Database.csproj" />
	</ItemGroup>

</Project>
