<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="MainWindow1.axaml.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="logo.jpg" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="appsettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="log4net.config">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="logo.jpg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="TOOLS.md">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Bodoconsult.App.Abstractions\Bodoconsult.App.Abstractions.csproj" />
		<ProjectReference Include="..\..\src\Bodoconsult.App.Avalonia.ReactiveUI\Bodoconsult.App.Avalonia.ReactiveUI.csproj" />
		<ProjectReference Include="..\..\src\Bodoconsult.App.Avalonia\Bodoconsult.App.Avalonia.csproj" />
		<ProjectReference Include="..\..\src\Bodoconsult.App\Bodoconsult.App.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.0" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="ReactiveUI.Avalonia" Version="12.0.3" />
		<PackageReference Include="ReactiveUI.SourceGenerators" Version="*" PrivateAssets="all" />
		<PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" Version="*" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="UserControls\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\..\LICENSE.md" Link="LICENSE.md" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Window2.axaml.cs">
	    <DependentUpon>Window2.axaml</DependentUpon>
	  </Compile>
	</ItemGroup>

</Project>
